apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Loki
    uid: loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false

  - name: Storage PostgreSQL
    uid: storage_pg
    type: postgres
    access: proxy
    url: postgres:5432
    user: postgres
    jsonData:
      database: pg_monitor_storage
      sslmode: "disable"
      postgresVersion: 1000
      timescaledb: false
    secureJsonData:
      password: postgres
    editable: false
